### ISSUE TITLE
String classes props ignored

### ISSUE THREAD

**Issue by clementmas** [solidjs/solid-transition-group#22]
Since the PR #18, the string classes `enterActiveClass`, `enterClass`, etc. passed as props are now ignored. 

These classes are instead always computed from the `name` props:
https://github.com/solidjs/solid-transition-group/blob/main/src/Transition.ts#L40

Which makes it impossible to use code like this (with TailwindCSS):
```jsx
<Transition
  enterActiveClass="transition duration-200"
  enterClass="opacity-0"
  enterToClass="opacity-100"
>
    ...
</Transition>
```

Whereas the documentation/readme says it's supported, as it should.

**Comment by adamjedlicka** [comment]
Yeah. This is a regression. Could this be fixed, please?

**Comment by ryansolid** [comment]
Alright try 0.0.12

**Comment by adamjedlicka** [comment]
@ryansolid Works like a charm. Thanks 🙂

**Comment by clementmas** [comment]
Yes, that's fixed. Thanks!
